services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: redes_server
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace
    networks:
      redes_net:
        ipv4_address: 172.28.0.2

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: redes_client
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace
    networks:
      redes_net:
        ipv4_address: 172.28.0.3

networks:
  redes_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16